# Generated by Django 5.1.7 on 2025-03-27 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_answer_question_possibleanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
